### ISSUE TITLE
Quoted heredoc delimiter gives parse error

### ISSUE THREAD

**Issue by Sjord** [tree-sitter/tree-sitter-php#104]
```
<?php

$header = <<<"EOD"
this is it
EOD;

var_dump($header);
```

Expected:

```
(program [0, 0] - [7, 0]
  (php_tag [0, 0] - [0, 5])
  (expression_statement [2, 0] - [4, 4]
    (assignment_expression [2, 0] - [4, 3]
      left: (variable_name [2, 0] - [2, 7]
        (name [2, 1] - [2, 7]))
      right: (heredoc [2, 9] - [4, 3])))
  (expression_statement [6, 0] - [6, 18]
    (function_call_expression [6, 0] - [6, 17]
      function: (name [6, 0] - [6, 8])
      arguments: (arguments [6, 8] - [6, 17]
        (argument [6, 9] - [6, 16]
          (variable_name [6, 9] - [6, 16]
            (name [6, 10] - [6, 16])))))))
```

Actual:

```
(program [0, 0] - [7, 0]
  (php_tag [0, 0] - [0, 5])
  (expression_statement [2, 0] - [4, 4]
    (binary_expression [2, 0] - [4, 3]
      left: (variable_name [2, 0] - [2, 7]
        (name [2, 1] - [2, 7]))
      (ERROR [2, 8] - [2, 11])
      (ERROR [2, 13] - [3, 10]
        (encapsed_string [2, 13] - [2, 18]
          (string [2, 14] - [2, 17]))
        (name [3, 0] - [3, 4])
        (name [3, 5] - [3, 7])
        (name [3, 8] - [3, 10]))
      right: (name [4, 0] - [4, 3])))
  (expression_statement [6, 0] - [6, 18]
    (function_call_expression [6, 0] - [6, 17]
      function: (name [6, 0] - [6, 8])
      arguments: (arguments [6, 8] - [6, 17]
        (argument [6, 9] - [6, 16]
          (variable_name [6, 9] - [6, 16]
            (name [6, 10] - [6, 16])))))))
test2.php	0 ms	(ERROR [2, 8] - [2, 11])
```

**Comment by cfroystad** [comment]
I've yet to look into it in detail (quite busy at the moment), but my current thinking is that since heredoc is basically a slightly more advanced double-quoted string in PHP, it should have the same node structure as the `encapsed_string`

The current heredoc implementation should (after some fixes) be a viable nowdoc implementation (disclaimer: unverified from the top of my head)

I'm not sufficiently familiar with the tree-sitter family to fully understand the ramifications of your last paragraph. Could you point me to some relevant documentation/example to help me understand this better. That way I'll try to account for it when I get started on this task

**Comment by Sjord** [comment]
We currently have this:

```
heredoc [2, 9] - [4, 3]
```

Which covers the entire thing. As I understand it, @claytonrcarter wants more like this:
```
(heredoc [2, 9] - [4, 3]
  start: name[2, 9] - [2,13]
  string: string[3, 0] - [3,30]
  end: name[4, 0] - [4, 3])
```

Then they can check the content of the start and end delimiters, and highlight in the correct language according to delimeters. E.g.

```
$a = <<< SQL
SELECT * FROM table
SQL; 
```

Here the contents of the heredoc will be highlighted as SQL, which is indicated by the delimiters. To implement this, they need an easy way to extract the delimiters from the parse tree.

**Comment by claytonrcarter** [comment]
Oh, a few hours later and that last paragraph of mine isn't clear at all, but yes @Sjord is correct on what I'm asking for. Thank you both!

**Comment by cfroystad** [comment]
It took a while before I found the time, but I think #121 provides what you asked for. Any additional testing and review would be great!

**Comment by claytonrcarter** [comment]
Thank you @cfroystad for this! I have not had a chance to actually play w/ it, but based on what I see in the test files, yes, this should work nicely for my needs. If I'm reading this correctly, I could look for any `heredoc` node, then use the value of `heredoc_start` to determine what, if any, language should be injected for highlighting/parsing of the `heredoc_body`. For example, if the author uses a heredoc identifier of `HTML`, I could instruct the editor to parse/highlight the contents of the heredoc as HTML.

If I get a chance to play with it before merge, I'll be sure to let you know what I find. Thanks again for working on this!
