### ISSUE TITLE
Parse-bug

### ISSUE THREAD

**Issue by codebear** [tree-sitter/tree-sitter-php#113]
I isolated a pretty simple piece of relatively straight forward valid PHP-code which is not parsed correctly.

```
function x($a, $b) {
    echo(" '$b' ");
    echo " '$a' ";
}
```
I tried tweaking it some but couldn't get a grasp on exactly where it fails.

**Comment by cfroystad** [comment]
The information about the `b''` syntax is well hidden in both the PHP documentation and the language specification.

> The optional b-prefix is reserved for future use in dealing with so-called binary strings. For now, a single-quoted-string-literal with a b-prefix is equivalent to one without.
[PHP specification - lexical structure](https://github.com/php/php-langspec/blob/8a7e96736ac18cdd159b7af2e7d1e4c666c9c822/spec/09-lexical-structure.md)

> (binary) casting and b prefix exists for forward support. Note that the (binary) cast is essential the same as (string), but it should not be relied upon. 
[PHP: Type juggeling](https://www.php.net/manual/en/language.types.type-juggling.php)

And it's no wonder that us mere mortals wonder about this, the current Mr. PHP himself, [wondered about the very same thing back in 2011](https://stackoverflow.com/questions/4749442/what-does-the-b-in-front-of-string-literals-do)

It will be interesting to see if the syntax will be deprecated eventually or if we'll be getting UTF-8 as default some time in the future. For now, there's been some heavy refactoring of PHP strings lately, but none of them touches this aspect. Priorly, there's been at least two ([Binary String Deprecation](https://wiki.php.net/rfc/binary_string_deprecation), [Deprecations for PHP 7.2](https://wiki.php.net/rfc/deprecations_php_7_2)) attempts at getting it deprecated, but for now it's not gotten the required votes.

Great that you might take a stab at it. Just ping me if you need any further assistance.

PS: Great to see another Norwegian in here 😄
