### ISSUE TITLE
UnaryExpression

### ISSUE THREAD

**Issue by codebear** [tree-sitter/tree-sitter-php#114]
I have a couple of questions or confusion regarding the definitions of unary expression in the grammar.

I put them in here together for å first _comment_, and if relevant, they can be split into different issues.

My understanding of the term unary expression is an expression with one operator and only one operand, opposed to a binary expression which typically have one operator and two operands.

## exponentiation_expression
Why is `exponentiation_expression` a part of `_unary_expression`?

Isn't `exponentiation_expression` a binary operation with the `left` expression being raised to the `right` exponent?

## unary_op_expression
For simpler analysis of the parsed tree, shouldn't a unary_op_expression have `field`-declarations?

I would find it natural that the operator was assigned to an `operator` field, and the expression being in `expr` field or similar.

I made a couple of attempts on this, but was only left with the fields being declared `required:false` in the node-types.json-file, indicating that I was not quite on the mark. I'm happy to share my attempts if this is an interesting route to take.

## error-control/silence-operator
I was at first a bit confused of the silence operator being a part of `unary_op_expression`.
I found this 4 year old commit which explicitly moved it there https://github.com/tree-sitter/tree-sitter-php/commit/acc53cd4482a9bc197aef43e1eb50f3df7ffa285, so i assume it was for good reasons?

Although one might argue that they both satisfy the one operator and one operand definition of unary expression, they don't share any logical common usage in the language?

Also due to the difference in precedence, perhaps they should have been held apart?

## child-type integer
This last thing is perhaps just my lack of tree-sitter understanding.

Why does the generated parser (at least according to `node-types.json`) result in a specific `integer` node as a child of `unary_op_expression`?

https://github.com/tree-sitter/tree-sitter-php/blob/master/src/node-types.json#L4328-L4331

**Comment by cfroystad** [comment]
I can only answer the two first questions right now, due to not knowing the answer to the remaining questions yet 🙂 

> Why is exponentiation_expression a part of _unary_expression?
> 
> Isn't exponentiation_expression a binary operation with the left expression being raised to the right exponent?

This would be my understanding as well, however, the [php specification explicitly lists exponentiation_expression](https://github.com/php/php-langspec/blob/master/spec/10-expressions.md#unary-operators) as an unary expression. I think this is wrong, but haven't opened a ticket about it to be proven either wrong or right yet. 
 
> ## unary_op_expression
> 
> For simpler analysis of the parsed tree, shouldn't a unary_op_expression have field-declarations?

Yes please! That's on my unofficial list of things to improve after correctness has improved, but I'll be happy if you'd like to contribute in that regard.

I'll come back to the remainder of the questions and very helpful comments when I have some time to investigate

**Comment by cfroystad** [comment]
It seems that the error control being placed under unary also comes from [the specification](https://github.com/php/php-langspec/blob/master/spec/10-expressions.md#unary-operators).

However, once again I believe the specification is wrong (to my knowledge it's not been too maintained after Facebook stopped targeting PHP with HHVM). [PHP-parser](https://github.com/nikic/PHP-Parser/blob/master/grammar/php7.y#L878) names this a top level expression.

**Comment by cfroystad** [comment]
> ## child-type integer

This is an error in the checked-in version of node-types.json

This is how it's supposed to look:

```
{
    "type": "exponentiation_expression",
    "named": true,
    "fields": {
      "left": {
        "multiple": false,
        "required": true,
        "types": [
          {
            "type": "_primary_expression",
            "named": true
          },
          {
            "type": "clone_expression",
            "named": true
          },
          {
            "type": "match_expression",
            "named": true
          },
          {
            "type": "unary_op_expression",
            "named": true
          }
        ]
      },
      "right": {
        "multiple": false,
        "required": true,
        "types": [
          {
            "type": "_primary_expression",
            "named": true
          },
          {
            "type": "assignment_expression",
            "named": true
          },
          {
            "type": "augmented_assignment_expression",
            "named": true
          },
          {
            "type": "clone_expression",
            "named": true
          },
          {
            "type": "exponentiation_expression",
            "named": true
          },
          {
            "type": "match_expression",
            "named": true
          },
          {
            "type": "unary_op_expression",
            "named": true
          }
        ]
      }
    }
  },
```

Building the grammar with `npm run build` should produce the same locally.
