### ISSUE TITLE
Parse predefined and magic constants

### ISSUE THREAD

**Issue by mikehaertl** [tree-sitter/tree-sitter-php#118]
Are there any plans to support parsing of predefined and magic constants?

* https://www.php.net/manual/en/reserved.constants.php
* https://www.php.net/manual/en/language.constants.magic.php

Or would this bloat the parser?

**Comment by patrickt** [comment]
I don't think we do this for any other language in the tree-sitter ecosystem. Do you have a use case in mind?

**Comment by mikehaertl** [comment]
>  Do you have a use case in mind?

Syntax highlighting. `@constant.builtin` is more specific than `@constant`.

**Comment by maxbrunsfeld** [comment]
You can do this with a ‘#match?’ predicate in the highlight query. I think we do something similar in the JavaScript highlight query for certain common JavaScript global s.

**Comment by mikehaertl** [comment]
@maxbrunsfeld Right, just figured that out too (https://github.com/nvim-treesitter/nvim-treesitter/pull/2303/files). I also wasn't aware that node type `constant` isn't provided by the parser.

I assume that there's a balance between "parse everything" and performance and that's why things like this aren't included in the parser? Or is it just because noone implemented it yet?

**Comment by maxbrunsfeld** [comment]
Two thoughts:

1. Should the parser recognize "constant" as its own type of node?

I'd be ok with doing this *type* of categorization in the parser, but I don't think there's an actual requirement in PHP that constants must be capitalized. It's just a heuristic (most of the time, constants are capitalized). I don't want the parser to include heuristics like this if we can avoid it, but I'm fine with doing it at the syntax highlighting layer.

2. Should the parser recognize *specific* built-in constants?

No; that's not the parser's job, and can't really be done efficiently at the parser level. That should be part of the "semantic" layer that builds on  top of the parser.

**Comment by mikehaertl** [comment]
> ... but I don't think there's an actual requirement in PHP that constants must be capitalized.

Correct. From [here](https://www.php.net/manual/en/language.constants.php): valid constant names are `^[a-zA-Z_\x80-\xff][a-zA-Z0-9_\x80-\xff]*$`.

So if I understand this right treesitter can not really recognize constants (unless with a heuristic like "all uppercase words")? I agree then that using match queries at the highlighting layer is the better option.
