### ISSUE TITLE
Php interpolation error

### ISSUE THREAD

**Issue by eduardoarandah** [tree-sitter/tree-sitter-php#124]
![image](https://user-images.githubusercontent.com/4065733/155226796-15695754-5cd3-4631-8edc-04b9308fe8e6.png)

parsing fails even on the simplest interpolation

code:

```
<div class="ok"> <?php "ok" ?> </div>
```

parsing:

```
text [0, 0] - [0, 17]
  element [0, 0] - [0, 16]
    start_tag [0, 0] - [0, 16]
      tag_name [0, 1] - [0, 4]
      attribute [0, 5] - [0, 15]
        attribute_name [0, 5] - [0, 10]
        quoted_attribute_value [0, 11] - [0, 15]
          attribute_value [0, 12] - [0, 14]
php_tag [0, 17] - [0, 22]
expression_statement [0, 23] - [0, 27]
  encapsed_string [0, 23] - [0, 27]
    string [0, 24] - [0, 26]
text_interpolation [0, 28] - [2, 0]
  text [0, 31] - [2, 0]
    ERROR [0, 31] - [0, 37]
      ERROR [0, 33] - [0, 36]

```

Platform:

nvim v0.6.1

Plugins (latest versions as today) 
Plug 'nvim-treesitter/nvim-treesitter'  (commit 3533721282669e945b62b3ae9c53d4c5ffe16c76)
Plug 'nvim-treesitter/playground' (commit 9df82a27a49e1c14e9d7416b537517a79d675086)

**Comment by maxbrunsfeld** [comment]
Neovim controls the interpolation. Can you open this issue on the nvim-treesitter repository?
