### ISSUE TITLE
Backtick operator does not parse interpolated variables

### ISSUE THREAD

**Issue by Sjord** [tree-sitter/tree-sitter-php#135]
The backtick execution operator can have variables that are interpolated, but these are not parsed.

```
<?php
`hello $world`;
```

Actual:
```
(program [0, 0] - [2, 0]
  (php_tag [0, 0] - [0, 5])
  (expression_statement [1, 0] - [1, 15]
    (shell_command_expression [1, 0] - [1, 14])))
```

Expected:
```
(program [0, 0] - [2, 0]
  (php_tag [0, 0] - [0, 5])
  (expression_statement [1, 0] - [1, 15]
    (shell_command_expression [1, 0] - [1, 14])))
      (string [1, 1] - [1, 7])
      (variable_name [1, 7] - [1, 13]
        (name [1, 8] - [1, 13])))))
```

**Comment by Sjord** [comment]
I created [some tests](https://github.com/Sjord/tree-sitter-php/blob/backtick-interpolation/test/corpus/backticks.txt) for this.

**Comment by cfroystad** [comment]
Beautiful! Thanks for the tests. This should be fairly straight forward once all the quirks in heredoc has been ironed out
