### ISSUE TITLE
Support PHP 8.2

### ISSUE THREAD

**Issue by cfroystad** [tree-sitter/tree-sitter-php#139]
Items will be added as they pass the RFC vote

- [x] [Add true type](https://wiki.php.net/rfc/true-type)
- [x] [Readonly classes](https://wiki.php.net/rfc/readonly_classes)
- [x] [Allow null and false as stand-alone types](https://wiki.php.net/rfc/null-false-standalone-types)
- [x] [Disjunctive Normal Form Types](https://wiki.php.net/rfc/dnf_types)
- [x] [Constants in Traits](https://wiki.php.net/rfc/constants_in_traits) (only tests needed)

PHP 8.2 is scheduled to be released on November 24th, 2022

**Comment by unansweredocd** [comment]
Once again, thanks for the work you folks are doing. Still hoping for the day for someone to release a laravel blade treesitter parser.

**Comment by unansweredocd** [comment]
I know it's offtopic but since you people seem to understand this stuff really well, I started a discussion about the thing I mentioned earlier which you can find [here](https://github.com/laravel/framework/discussions/45286) and I would love your help.

**Comment by gbprod** [comment]
I've tried to implements [Disjunctive Normal Form Types](https://wiki.php.net/rfc/dnf_types) but it seems too hard for me :sweat_smile: 
Does somebody can try to implements this ? It will be make the parser compliant with php 8.2 :pray:
