### ISSUE TITLE
Consufsing about ADDITIONALLIBS on linux machines

### ISSUE THREAD

**Issue by rever1and** [tree-sitter/tree-sitter-php#152]
Hi, I'm using the c binding so tried to build on my machine.

What's the reason for `ADDITIONALLIBS=-lc++`? I struggled with removing this to successfully build on a linux machine(ubuntu 20.04).

I'm not sure..if the dynamic library really work as expected after. But linked the static archive so just link with it with `-lstdc++` works well.

**Comment by piotrkwiecinski** [comment]
Little late response. For people coming in here. There was a typo in a Makefile.

It was fixed in: https://github.com/tree-sitter/tree-sitter-php/pull/174

After installing additional dependencies:

```
sudo apt install libc++abi-dev libc++-dev
```
I was able to run make successfully on ubuntu.
