### ISSUE TITLE
.php HTML/CSS/JS highlighting

### ISSUE THREAD

**Issue by iskrisis** [tree-sitter/tree-sitter-php#153]
I've been trying out Lapce and the php highlighting works well in .php file but .php is also templating language and thus it can be mixed with like html, CSS or even JS.
This work well in VSCode which somehow seem to understand any mixture of languages mashed together.

Wondering if this something that could somehow work some day?

**Comment by rever1and** [comment]
I do not use Lapce, but sounds like a implementation problem of Lapce. maybe one could try this:

https://tree-sitter.github.io/tree-sitter/using-parsers#multi-language-documents

**Comment by iskrisis** [comment]
@rever1and thank you. I will put this to Lapce repo.
