### ISSUE TITLE
PHP tags closed preceding a `#` character cause the rest of the line to interpret as a comment

### ISSUE THREAD

**Issue by logancollins** [tree-sitter/tree-sitter-php#156]
Apologies if this ends up being an issue _outside_ of the PHP parser itself. I've spent some time digging into this and am _pretty sure_ that's where the issue lies.

We've found a case where having a PHP tag inline in, say, an HTML attribute in a mixed-mode document where the tag immediately precedes a `#` character (such as when used as an anchor ID) will cause the rest of the line to be consumed as a PHP comment, despite the `#` being outside of the PHP tag's closing marker.

Even when disabling the HTML injections for the language, the rest of lines are still parsed as `(comment)` in the PHP rules, which is what led me to believe this is centered in the PHP grammar.

Thank you for your time!

Example file: 
[example.php.zip](https://github.com/tree-sitter/tree-sitter-php/files/10179337/example.php.zip)

Reproduced in the [Nova 10.4](https://nova.app) editor using a PHP grammar from the main branch of `tree-sitter-php` built as of November.

<img width="411" alt="Screenshot 2022-12-07 at 11 19 35 AM" src="https://user-images.githubusercontent.com/714246/206275855-47f2f2a0-5ed0-4da9-b360-be7f1084c45b.png">
<img width="555" alt="Screenshot 2022-12-07 at 11 19 40 AM" src="https://user-images.githubusercontent.com/714246/206275862-d695fc80-a027-47cf-808b-174b4d8c84eb.png">

**Comment by rever1and** [comment]
After sometime to inspect this, I think the `$.comment` should not in `extras`, but may need to manually insert into everywhere it needs.
