### ISSUE TITLE
`array` as a named parameter causes error

### ISSUE THREAD

**Issue by przepompownia** [tree-sitter/tree-sitter-php#161]
Consider the following code:
```php
<?php

$a = [];

array_map(array: $a, 'intval');
```
I get
```
php_tag [0, 0] - [0, 5]
expression_statement [2, 0] - [2, 8]
  assignment_expression [2, 0] - [2, 7]
    left: variable_name [2, 0] - [2, 2]
      name [2, 1] - [2, 2]
    right: array_creation_expression [2, 5] - [2, 7]
expression_statement [4, 0] - [4, 31]
  function_call_expression [4, 0] - [4, 30]
    function: name [4, 0] - [4, 9]
    arguments: arguments [4, 9] - [4, 30]
      ERROR [4, 10] - [4, 16]
      argument [4, 17] - [4, 19]
        variable_name [4, 17] - [4, 19]
          name [4, 18] - [4, 19]
      argument [4, 21] - [4, 29]
        string [4, 21] - [4, 29]
          string_value [4, 22] - [4, 28]
```

**Comment by rever1and** [comment]
Maybe it is not the best way but it works.

```
diff --git a/grammar.js b/grammar.js
index 601ceba..fb7646f 100644
--- a/grammar.js
+++ b/grammar.js
@@ -1125,7 +1125,7 @@ module.exports = grammar({
     ),
 
     argument: $ => seq(
-      optional(seq(field('name', $.name), ':')),
+      optional(seq(field('name', choice(alias($.cast_type, $.name), $.name)), ':')),
       optional(field('reference_modifier', $.reference_modifier)),
       choice(alias($._reserved_identifier, $.name), $.variadic_unpacking, $._expression)
     ),
```

by the way, as far as i know, you can't put positional args after named arguments.

**Comment by przepompownia** [comment]
The original example had `callback:` and it should be here although it doesn't seem to matter for this issue. 

In free time I'll try to built the changes above.

**Comment by przepompownia** [comment]
I gave up (not the first time) after not finding what I have missing to build or use already built library using nvim-treesitter. 
```
 Error executing vim.schedule lua callback: Failed to load parser: uv_dlopen: /home/arctgx/.vim/pack/bundle/opt/nvim-treesitter/parser/php.so: undefined symbol: tree_sitter_php_external_scanner_create
```

**Comment by przepompownia** [comment]
Independently of the value of `ADDITIONALLIBS` it looks for me like no problem with `TSInstallFromGrammar php` but with loading the recent built library.

**Comment by rever1and** [comment]
> Independently of the value of `ADDITIONALLIBS` it looks for me like no problem with `TSInstallFromGrammar php` but with loading the recent built library.
> 
> Built on Debian Sid.

Sorry, I dont know much about neovim. I just regenerate gramar.json and  verify tree-sitter-php build with tree-sitter-cli. As for build problem, that may relates to how neovim-treesitter link tree-sitter and tree-sitter-php, you may need ask for help in its community.

**Comment by przepompownia** [comment]
@rever1and I found a while to find the correct configuration and see it works:

![image](https://user-images.githubusercontent.com/11404453/213239380-e1939f5b-939a-4e19-8963-7a9d09d25a48.png)

```lua
local parserConfig = require 'nvim-treesitter.parsers'.get_parser_configs()
parserConfig.php = {
  install_info = {
    url = '~/dev/external/tree-sitter-php',
    files = {'src/parser.c', 'src/scanner.cc'},
    branch = 'array',
    generate_requires_npm = false,
    requires_generate_from_grammar = false,
  },
  filetype = 'php',
}
```
Would you like to create PR with the suggested change?

**Comment by rever1and** [comment]
> @rever1and I found a while to find the correct configuration and see it works:
> 
> ![image](https://user-images.githubusercontent.com/11404453/213239380-e1939f5b-939a-4e19-8963-7a9d09d25a48.png)
> 
> ```lua
> local parserConfig = require 'nvim-treesitter.parsers'.get_parser_configs()
> parserConfig.php = {
>   install_info = {
>     url = '~/dev/external/tree-sitter-php',
>     files = {'src/parser.c', 'src/scanner.cc'},
>     branch = 'array',
>     generate_requires_npm = false,
>     requires_generate_from_grammar = false,
>   },
>   filetype = 'php',
> }
> ```
> 
> Would you like to create PR with the suggested change?

I'll try later

**Comment by calebdw** [comment]
This is being caused by the `array` keyword in the `array_creation_expression`---doesn't happen for the other types or type casts:

https://github.com/tree-sitter/tree-sitter-php/blob/594b8bad093abe739c3d2a2cae5abae33c5fb23d/grammar.js#L1190-L1193

I tried playing around with precedence rules but didn't get very far...

**Comment by calebdw** [comment]
This does fix the issue but seems a little clunky:

```diff
      argument: $ => seq(
-       optional(seq(field('name', $.name), ':')),
+       optional(seq(field('name', choice($.name, alias(keyword('array'), $.name))), ':')),
        optional(field('reference_modifier', $.reference_modifier)),
        choice(alias($._reserved_identifier, $.name), $.variadic_unpacking, $._expression),
      ),
```

Thoughts @cfroystad? I can PR this fix if its acceptable or am open ears for better ideas.

**Comment by calebdw** [comment]
After more digging I've discovered that the optional argument name is conflicting with almost any `_expression` that starts with a `keyword()` as part of its sequence---the following is a list of identifiers that don't work as named arguments:

- `array`
- `static`
- `self`
- `parent`
- `namespace`
- `function`
- `fn`
- `match`
- `true`
- `false`
- `null`

**Comment by przepompownia** [comment]
It works, thanks!
