### ISSUE TITLE
Comments on class properties causes error

### ISSUE THREAD

**Issue by calind** [tree-sitter/tree-sitter-php#163]
![Screenshot 2022-12-26 at 18 50 43](https://user-images.githubusercontent.com/266375/209569228-74e9770b-c7cd-4b43-a225-749dab37e08a.png)

**Comment by rever1and** [comment]
hi, I tried https://tree-sitter.github.io/tree-sitter/playground find it should not error?

![Screenshot from 2023-01-05 18-17-18](https://user-images.githubusercontent.com/53398061/210756728-2f778cc2-b6c1-42ad-85ce-866d97963076.png)

**Comment by calind** [comment]
Errors are because of incomplete https://github.com/claytonrcarter/tree-sitter-phpdoc.
