### ISSUE TITLE
"for" keyword is no longer highlighted

### ISSUE THREAD

**Issue by TheWitheredStriker** [tree-sitter/tree-sitter-php#165]
See examples:

https://github.com/PHPMailer/PHPMailer/blob/master/src/PHPMailer.php#L1841

https://github.com/nawarian/raylib-ffi/blob/6e748edac33afb6a99260c911c727213a574d89b/examples/shapes/shapes_easings_rectangle_array.php#L40

Not really sure why this occurs (came here from Linguist, which listed this grammar as the used grammar for PHP on GitHub), but I figured I should report this.

**Comment by rever1and** [comment]
Maybe you can just add it to `highlights.scm` if you needed it locally

**Comment by calebdw** [comment]
This works for me locally, not sure why the github links aren't highlighting them (nothing really to do here).

![image](https://github.com/tree-sitter/tree-sitter-php/assets/4176520/10d2129e-57c4-4040-9ff9-ceecda78553d)

**Comment by calebdw** [comment]
Unless you want to add `for` to the list of keywords:

https://github.com/tree-sitter/tree-sitter-php/blob/594b8bad093abe739c3d2a2cae5abae33c5fb23d/queries/highlights.scm#L99
