### ISSUE TITLE
Dynamically inject languages into {here,now}docs

### ISSUE THREAD

**Issue by CalebDW** [tree-sitter/tree-sitter-php#167]
Hello!

Would it be possible to add injection queries for heredocs and nowdocs?

Thanks!

**Comment by gbprod** [comment]
You can find the injections queries for that here : https://github.com/nvim-treesitter/nvim-treesitter/blob/master/queries/php/injections.scm#L8-L18

**Comment by CalebDW** [comment]
Yes,  I PRd those queries
