### ISSUE TITLE
Inject PHP code without PHP tags

### ISSUE THREAD

**Issue by calebdw** [tree-sitter/tree-sitter-php#168]
Hello!

I'm trying (somewhat unsuccessfully, but trying nonetheless) to write a parser for the [Laravel Blade](https://laravel.com/docs/master/blade) templating system. I've captured the code content between the output directives (e.g., `{{ $fooBar->some_attribute }}`) but when I inject the content the parser thinks it (`$fooBar->some_attribute`) is just text.

If I do the following then the parser recognizes it as a variable and properly highlights it, however, this defeats the whole purpose of the templating system:
`{{ <?php $fooBar->some_attribute ?> }}`

Something similar occurs in markdown file with PHP fenced content:

E.g., here the php parser thinks the content is just text
![image](https://user-images.githubusercontent.com/4176520/220391757-0c98c24f-d86f-4fef-9e04-3e269d24464e.png)

whereas it's a variable assignment with the php tags
![image](https://user-images.githubusercontent.com/4176520/220391848-0a007271-80fb-4a23-9dca-cf7c0ff34c25.png)

Is there a way to have the parser recognize the content as php without explicitly declaring the php tags?

Thanks!

**Comment by CalebDW** [comment]
It looks like the Go parser allows statements at the top level for this very reason (https://github.com/tree-sitter/tree-sitter-go/issues/63).

I'll submit a PR to do the same with this parser.
