### ISSUE TITLE
Implement php_sql_query functionality from vim php syntax highlighting

### ISSUE THREAD

**Issue by jthemenace** [tree-sitter/tree-sitter-php#183]
I've tried to get the functionality of php_sql_query "SQL syntax highlighting inside strings" that is provided by the built in php syntax highlighting for neovim to work in Tree Sitter.  Using injections from https://github.com/gbprod/php-enhanced-treesitter.nvim it's really close.  However, whenever I reference a variable in a query in a string, for the rest of that string the syntax highlighting is broken.

Any chance this functionality could be implemented, or suggestion on how to get it to work with injections and overcome the variable issue?

Example below, syntax highlighting breaks when hitting $item.

Thank you for your consideration and any help you can offer.

```
<?php 
$db = new mysqli(“localhost”,”user”,”pass”); 
$query = “SELECT item FROM prodmast WHERE item='$item' AND class='02'”; 
$result = $db->query($query); $row = $result->fetch_assoc();
```

**Comment by calebdw** [comment]
You could try to use the [Curly Syntax](https://www.php.net/manual/en/language.types.string.php#language.types.string.parsing.complex):

```php
$query = "SELECT item FROM prodmast WHERE item='{$item}' AND class='02'"; 
// vs
$query = "SELECT item FROM prodmast WHERE item='$item' AND class='02'"; 
```

But the preferred method of language injection is through heredocs/nowdocs which is fully supported without any additional plugins:

![image](https://github.com/tree-sitter/tree-sitter-php/assets/4176520/4d64848e-165f-479a-aa64-2cd476906eb9)

granted, the php variable is highlighted as a string as the sql injections takes precedence, but it's better than the rest of the sytax highlighting being broken.

**Comment by calebdw** [comment]
@cfroystad, not sure that there's anything to be done here---can this be closed?

**Comment by amaanq** [comment]
(psst @calebdw, do you mind checking discord or do you have somewhere I could chat w/ you for a bit? only good things of course :^) )
