### ISSUE TITLE
Tests fails in local on master

### ISSUE THREAD

**Issue by gbprod** [tree-sitter/tree-sitter-php#186]
Hello,

It seems that since [this commit](https://github.com/tree-sitter/tree-sitter-php/commit/6cd93c96fde2aef0da13a2948cadab0bd3e96895) I'm not able to successfully build and run tests on my machine.

I use the latest tree-sitter-cli version from npm (0.20.8), what I'm I missing ?

Thanks

**Comment by amaanq** [comment]
node/npm is outdated until there's a new release, use the rust cli app on master
