### ISSUE TITLE
tree-sitter generate: generating test-wrong code

### ISSUE THREAD

**Issue by ArmProg-San** [tree-sitter/tree-sitter-php#188]
Hello, I ran the tree-sitter test code, and it passed all tests. However, after running tree-sitter generate for tree-sitter-php, when I ran the test using tree-sitter test, the code couldn't pass several tests.
`tree-sitter test
  statements:
    ✓ If statements
    ✓ Alternative if statements
    ✓ Wordpress colon blocks
    ✓ While statements
    ✓ Alternative while statements
    ✓ For statements
    ✓ Switch statements
    ✓ Alternative switch statements
    ✓ Include statement
    ✓ Do-while statements
    ✓ Try statements
    ✓ Foreach statements
    ✓ Case insensitive keywords
    ✓ Accessing Constants
  expressions:
    ✓ Dynamic variable names
    ✓ Exponentiation
    ✓ Reserved Identifiers as Names
    ✓ Unary op with assignment expressions
    ✓ Capitalized logical operators
    ✓ Cast expressions in assignments
    ✓ Cast include
    ✓ Reserved words as function calls
    ✓ Scoped self call expressions
    ✓ Symmetric array destructuring
    ✓ Precedence of assignment, `or`, `xor`, and `and`
    ✓ Associativity of conditional
    ✓ Associativity of null-coalescence
    ✓ Associativity of negation
    ✓ Augmented assignment
    ✓ Nested assignemnts
    ✓ All binary op precedence levels
    ✓ Concatenation precedence
    ✓ Arrays
    ✓ Anonymous functions
    ✓ Throw expressions
    ✓ Nullsafe operator
    ✓ First class callable syntax
    ✓ Match expressions
    ✓ Arrow functions
    ✓ Functions with named arguments
    ✓ Precedence between concatenation and shift
    ✓ References
    ✓ Empty match expressions
  literals:
    ✓ Booleans
    ✓ Floats
    ✓ Integers
    ✓ Testing string scanner confirmance
    ✓ Shell command
  execution_operator:
    ✓ Quotes in backticks
    ✓ Escape sequences in backticks
    ✓ Variable interpolation in backticks
    ✓ Member access expression in backticks
    ✓ Array subscript expression in backticks
    ✓ Complex interpolation in backticks
    ✓ Nesting of expression in backticks
    ✓ Nested escaped backticks
    ✓ Comment in backticks
  string:
    ✓ Complex: Variable access
    ✓ Complex: Disallow space between { and $
    ✓ Complex: PHP documentation tests
    ✓ Simple: Variable access
    ✓ Simple: Member and array access
    ✓ Corner cases
    ✓ Single quoted
    ✓ Bug: #113
    ✓ Heredocs
    ✓ Nowdocs
    ✓ Unicode escape sequences
  class:
    ✓ Abstract class
    ✓ Anonymous classes
    ✓ Conditional class definition
    ✓ Class constant modifiers
    ✓ Final class
    ✓ Implicitly public properties and methods
    ✓ Property Types
    ✓ Constructor Property Promotion
    ✓ Readonly properties
    ✓ Constructor property promotion with readonly modifier
    ✓ Readonly class
    ✓ Constants in trait
  types:
    ✓ Type names
    ✓ Primitive types
    ✓ Intersection type
    ✓ Optional types
    ✓ Union types
    ✓ Mixed type
    ✓ Static type
    ✓ Null type
    ✓ False type
    ✓ True type
  bugs:
    ✓ #131: Parse error when using self as constant
    ✓ #133: Incorrect precedence for error supression operator
  interpolation:
    ✓ no interpolated text
    ✓ interpolated text at beginning
    ✓ interpolated text at end
    ✓ interpolated text in middle
    ✓ short open tag: On
    ✓ short open tag: Off
    ✓ Single line php comment
    ✓ Singel line comment without any content
    ✓ Closing tags before the first PHP tag
  declarations:
    ✓ Interface declarations
    ✓ Use declarations
    ✓ Namespace names in namespaces
    ✓ Class declarations
    ✓ Class declarations with base classes
    ✓ Function parameters
    ✓ Functions with default parameters
    ✓ Static variables in functions
    ✓ Defining Constants
    ✓ Attributes
    ✓ Enums
syntax highlighting:
  ✓ literals.php (7 assertions)
  ✓ types.php (3 assertions)
  ✓ keywords.php (18 assertions)`
  
after generate:
`
  statements:
    ✓ If statements
    ✓ Alternative if statements
    ✓ Wordpress colon blocks
    ✓ While statements
    ✓ Alternative while statements
    ✓ For statements
    ✓ Switch statements
    ✓ Alternative switch statements
    ✓ Include statement
    ✓ Do-while statements
    ✓ Try statements
    ✓ Foreach statements
    ✗ Case insensitive keywords
    ✓ Accessing Constants
  expressions:
    ✓ Dynamic variable names
    ✓ Exponentiation
    ✓ Reserved Identifiers as Names
    ✓ Unary op with assignment expressions
    ✗ Capitalized logical operators
    ✓ Cast expressions in assignments
    ✓ Cast include
    ✓ Reserved words as function calls
    ✓ Scoped self call expressions
    ✓ Symmetric array destructuring
    ✓ Precedence of assignment, `or`, `xor`, and `and`
    ✓ Associativity of conditional
    ✗ Associativity of null-coalescence
    ✓ Associativity of negation
    ✓ Augmented assignment
    ✓ Nested assignemnts
    ✓ All binary op precedence levels
    ✓ Concatenation precedence
    ✓ Arrays
    ✓ Anonymous functions
    ✓ Throw expressions
    ✓ Nullsafe operator
    ✓ First class callable syntax
    ✓ Match expressions
    ✓ Arrow functions
    ✓ Functions with named arguments
    ✓ Precedence between concatenation and shift
    ✓ References
    ✓ Empty match expressions
  literals:
    ✓ Booleans
    ✓ Floats
    ✓ Integers
    ✓ Testing string scanner confirmance
    ✓ Shell command
  execution_operator:
    ✓ Quotes in backticks
    ✓ Escape sequences in backticks
    ✓ Variable interpolation in backticks
    ✓ Member access expression in backticks
    ✓ Array subscript expression in backticks
    ✓ Complex interpolation in backticks
    ✓ Nesting of expression in backticks
    ✓ Nested escaped backticks
    ✓ Comment in backticks
  string:
    ✓ Complex: Variable access
    ✓ Complex: Disallow space between { and $
    ✓ Complex: PHP documentation tests
    ✓ Simple: Variable access
    ✓ Simple: Member and array access
    ✓ Corner cases
    ✓ Single quoted
    ✓ Bug: #113
    ✓ Heredocs
    ✓ Nowdocs
    ✓ Unicode escape sequences
  class:
    ✓ Abstract class
    ✓ Anonymous classes
    ✓ Conditional class definition
    ✓ Class constant modifiers
    ✓ Final class
    ✓ Implicitly public properties and methods
    ✓ Property Types
    ✓ Constructor Property Promotion
    ✗ Readonly properties
    ✓ Constructor property promotion with readonly modifier
    ✓ Readonly class
    ✓ Constants in trait
  types:
    ✓ Type names
    ✓ Primitive types
    ✓ Intersection type
    ✓ Optional types
    ✓ Union types
    ✓ Mixed type
    ✓ Static type
    ✓ Null type
    ✓ False type
    ✓ True type
  bugs:
    ✓ #131: Parse error when using self as constant
    ✓ #133: Incorrect precedence for error supression operator
  interpolation:
    ✓ no interpolated text
    ✓ interpolated text at beginning
    ✓ interpolated text at end
    ✓ interpolated text in middle
    ✓ short open tag: On
    ✓ short open tag: Off
    ✓ Single line php comment
    ✓ Singel line comment without any content
    ✓ Closing tags before the first PHP tag
  declarations:
    ✓ Interface declarations
    ✓ Use declarations
    ✓ Namespace names in namespaces
    ✓ Class declarations
    ✓ Class declarations with base classes
    ✓ Function parameters
    ✓ Functions with default parameters
    ✓ Static variables in functions
    ✓ Defining Constants
    ✓ Attributes
    ✓ Enums

4 failures:

expected / actual

  1. Case insensitive keywords:

    (program
      (php_tag)
      (expression_statement
        (subscript_expression
          (function_call_expression
            (name)
            (arguments
              (argument
                (dynamic_variable_name
                  (ERROR
                    (name)
                    (name))
      (foreach_statement
        (variable_name
          (name))
        (variable_name
          (name))
        (compound_statement
          (do_statement
            (compound_statement
              (if_statement
                (parenthesized_expression
                  (variable_name
                    (name))))))
          (function_call_expression
            (subscript_expression
              (name)
              (subscript_expression
                (subscript_expression
                  (function_call_expression
                    (name)
                    (arguments
                      (argument
                        (variable_name
                          (name)))))
                  (function_call_expression
                    (name)
                    (arguments))
                  (ERROR))
                (ERROR
                  (name))
                (function_call_expression
                  (name)
                  (arguments))
                (ERROR)))
            (ERROR
              (name))
            (arguments
              (argument
                (variable_name
                  (name)))))
          (ERROR))
        (MISSING ";")))
                    (name)))
                (compound_statement
                  (expression_statement
                    (function_call_expression
                      (name)
                      (arguments))))
                (else_clause
                  (compound_statement
                    (expression_statement
                      (function_call_expression
                        (name)
                        (arguments)))))))
            (parenthesized_expression
              (variable_name
                (name)))))))

  2. Capitalized logical operators:

    (program
      (php_tag)
      (expression_statement
        (function_call_expression
          (name)
          (arguments
            (ERROR
              (name))
            (argument
              (function_call_expression
                (function_call_expression
                  (name)
                  (arguments))
                (ERROR
                  (name)
                  (name))
                (arguments)))
            (MISSING ")))))
        (binary_expression
          (function_call_expression
            (name)
            (arguments))
          (binary_expression
            (function_call_expression
              (name)
              (arguments))
            (function_call_expression
              (name)
              (arguments))))))

  3. Associativity of null-coalescence:

    (program
      (php_tag)
      (expression_statement
        (binary_expression
          (name)
          (null)
          (binary_expression
            (name)
            (null)
            (integer))))
      (text_interpolation))

  4. Readonly properties:

    (program
      (php_tag)
      (class_declaration
        (name)
        (declaration_list
          (property_declaration
            (visibility_modifier)
            (readonly_modifier)
            (union_type
              (primitive_type))
            (property_element
              (variable_name
                (name))))
          (property_declaration
            (visibility_modifier)
            (readonly_modifier)
            (union_type
              (primitive_type))
            (property_element
              (variable_name
                (name))))
          (property_declaration
            (visibility_modifier)
            (readonly_modifier)
            (union_type
              (primitive_type))
            (property_element
              (variable_name
                (name))))
          (property_declaration
            (visibility_modifier)
            (readonly_modifier)
            (union_type
              (primitive_type))
            (property_element
              (variable_name
                (name))))
          (property_declaration
            (visibility_modifier)
            (readonly_modifier)
            (union_type
              (named_type
                (name)))
            (property_element
              (variable_name
                (name))))
          (property_declaration
            (readonly_modifier)
            (visibility_modifier)
            (union_type
              (primitive_type))
            (property_element
              (variable_name
                (name))))
          (property_declaration
            (readonly_modifier)
            (visibility_modifier)
            (union_type
              (primitive_type))
            (property_element
              (variable_name
                (name))))
          (property_declaration
            (readonly_modifier)
            (visibility_modifier)
            (union_type
              (primitive_type))
            (property_element
              (variable_name
                (name))))
          (property_declaration
            (readonly_modifier)
            (visibility_modifier)
            (union_type
              (primitive_type))
            (property_element
              (variable_name
                (name))))
          (property_declaration
            (readonly_modifier)
            (visibility_modifier)
            (union_type
              (named_type
                (name)))
            (property_element
              (variable_name
                (name))))
          (property_declaration
            (visibility_modifier)
            (readonly_modifier)
            (union_type
              (primitive_type))
            (property_element
              (variable_name
                (name))))
          (property_declaration
            (visibility_modifier)
            (readonly_modifier)
            (union_type
              (primitive_type))
            (property_element
              (variable_name
                (name))))
          (property_declaration
            (visibility_modifier)
            (readonly_modifier)
            (union_type
              (primitive_type))
            (property_element
              (variable_name
                (name))))
          (property_declaration
            (visibility_modifier)
            (readonly_modifier)
            (union_type
              (primitive_type))
            (property_element
              (variable_name
                (name))))
          (property_declaration
            (visibility_modifier)
            (readonly_modifier)
            (union_type
              (named_type
                (name)))
            (property_element
              (variable_name
                (name))))
          (property_declaration
            (readonly_modifier)
            (visibility_modifier)
            (union_type
              (primitive_type))
            (property_element
              (variable_name
                (name))))
          (property_declaration
            (readonly_modifier)
            (visibility_modifier)
            (union_type
              (primitive_type))
            (property_element
              (variable_name
                (name))))
          (property_declaration
            (readonly_modifier)
            (visibility_modifier)
            (union_type
              (primitive_type))
            (property_element
              (variable_name
                (name))))
          (property_declaration
            (readonly_modifier)
            (visibility_modifier)
            (union_type
              (primitive_type))
            (property_element
              (variable_name
                (name))))
          (property_declaration
            (readonly_modifier)
            (visibility_modifier)
            (union_type
              (named_type
                (name)))
            (property_element
              (variable_name
                (name))))
          (property_declaration
            (visibility_modifier)
            (readonly_modifier)
            (union_type
              (primitive_type))
            (property_element
              (variable_name
                (name))))
          (property_declaration
            (visibility_modifier)
            (readonly_modifier)
            (union_type
              (primitive_type))
            (property_element
              (variable_name
                (name))))
          (property_declaration
            (visibility_modifier)
            (readonly_modifier)
            (union_type
              (primitive_type))
            (property_element
              (variable_name
                (name))))
          (property_declaration
            (visibility_modifier)
            (readonly_modifier)
            (union_type
              (primitive_type))
            (property_element
              (variable_name
                (name))))
          (property_declaration
            (visibility_modifier)
            (readonly_modifier)
            (union_type
              (named_type
                (name)))
            (property_element
              (variable_name
                (name))))
          (property_declaration
            (readonly_modifier)
            (visibility_modifier)
            (union_type
              (primitive_type))
            (property_element
              (variable_name
                (name))))
          (property_declaration
            (readonly_modifier)
            (visibility_modifier)
            (union_type
              (primitive_type))
            (property_element
              (variable_name
                (name))))
          (property_declaration
            (readonly_modifier)
            (visibility_modifier)
            (union_type
              (primitive_type))
            (property_element
              (variable_name
                (name))))
          (property_declaration
            (readonly_modifier)
            (visibility_modifier)
            (union_type
              (primitive_type))
            (property_element
              (variable_name
                (name))))
          (property_declaration
            (readonly_modifier)
            (visibility_modifier)
            (union_type
              (named_type
                (name)))
            (property_element
              (variable_name
                (name))))
          (property_declaration
            (readonly_modifier)
            (union_type
              (primitive_type))
            (property_element
              (variable_name
                (name))))
          (property_declaration
            (readonly_modifier)
            (union_type
              (primitive_type))
            (property_element
              (variable_name
                (name))))
          (property_declaration
            (readonly_modifier)
            (union_type
              (primitive_type))
            (ERROR
              (property_element
                (variable_name
                  (name)))
              (name)
              (property_element
                (variable_name
                  (name)))
              (name))
            (property_element
              (variable_name
                (name))))
          (property_declaration
            (readonly_modifier)
            (union_type
              (primitive_type))
            (property_element
              (variable_name
                (name))))
          (property_declaration
            (readonly_modifier)
            (union_type
              (named_type
                (name)))
            (property_element
              (variable_name
                (name)))))))`

---------------------------
node: v20.8.0
npm: 10.1.0
tree-sitter: 0.20.8
tree-sitter-php: 0.19.0
nan: 2.18.0

**Comment by gbprod** [comment]
Seems that is the same problem than #186 , using rust client fixed for me.

**Comment by ArmProg-San** [comment]
> Seems that is the same problem than #186 , using rust client fixed for me.

Can you please add verbosity if it possible?

**Comment by gbprod** [comment]
I assume that you are using npm to install `tree-sitter-cli`, it's outdated, you should use the `tree-sitter-cli` provided by `cargo`. Refer to the documentation for installation : https://github.com/tree-sitter/tree-sitter/tree/master/cli

In my case, I used the command : `cargo install --git https://github.com/tree-sitter/tree-sitter/`

**Comment by ArmProg-San** [comment]
I also tried `cargo install tree-sitter-cli`  and , but I obtained the same result.
