### ISSUE TITLE
Add separate highlighting for "$" being part of variable

### ISSUE THREAD

**Issue by DanielSiepmann** [tree-sitter/tree-sitter-php#189]
Hey all, I'm still very new to tree-sitter.

I use it within Neovim and am used to a different highlighting of the "$" sign as prefix of variable names.
But using tree-sitter the "$" is part of the "variable" highlighting. I saw https://github.com/tree-sitter/tree-sitter-php/blob/master/queries/highlights.scm#L73 but that's not coming up in Neovim. There "$" is part of variable. Is there any way to split this up to allow separate styling of the "$" again?

Any help is appreciated.

This is how my old theme prior tree-sitter looked like:
![image](https://github.com/tree-sitter/tree-sitter-php/assets/354250/3526a37c-27dd-4697-9d44-343a5ce9abff)

This is how my theme looks like with tree-sitter:
![image](https://github.com/tree-sitter/tree-sitter-php/assets/354250/6de279fa-641e-44c8-a8fe-6d0b0207c43f)

**Comment by gbprod** [comment]
Hi @DanielSiepmann,

This is possible by extending default php highlight, you have the required code [here](https://github.com/gbprod/php-enhanced-treesitter.nvim/blob/main/queries/php/highlights.scm#L6-L8) : 

```query
;; extends

[
 "$"
] @keyword
```

You can create your own custom queries by using the command `:TSEditQueryUserAfter php`  (or you can use [my plugin](https://github.com/gbprod/php-enhanced-treesitter.nvim)  :wink:)

**Comment by DanielSiepmann** [comment]
Thanks @gbprod that was exactly what I was looking for. Thanks for sharing your plugin.
I couldn't find proper dos on Neovim on how exactly to extend the queries and how this would work.

(It drove me crazy to not have the different highlighting, I'm just used to it and need another colour between all the same colours. You made my day :)
