### ISSUE TITLE
Broken tests on master?

### ISSUE THREAD

**Issue by calebdw** [tree-sitter/tree-sitter-php#191]
Hello!

Maybe it's just me, but there are 4 tests currently failing on `master`. Git bisect shows that @amaanq's commit 6cd93c96fde2aef0da13a2948cadab0bd3e96895 is the culprit (at least for some of the broken tests).

### Steps to Reproduce:
I'm using:
Node: v20.8.1
Tree-sitter: 0.20.8

1. checkout master
2. `npm install`
3. `npm run build`
4. `npm run test`
5. fail

Running the above commands produces a diff on the generated files which suggests they weren't regenerated after one of the more recent commits.

![image](https://github.com/tree-sitter/tree-sitter-php/assets/4176520/5f678fda-2215-4f48-80cb-d39299db7906)

Interestingly, I'm seeing the `i` flags being removed from the `grammar.json` which is likely the cause for some of the broken tests...

#### Case insensitive keywords

<details>

![image](https://github.com/tree-sitter/tree-sitter-php/assets/4176520/afc23f52-8475-4960-9fa9-f7c007ad7c54)
![image](https://github.com/tree-sitter/tree-sitter-php/assets/4176520/8eb001f9-2f78-4adc-9e63-fb88554cf600)

</details>

#### Readonly properties
<details>

![image](https://github.com/tree-sitter/tree-sitter-php/assets/4176520/0dc49f02-c3ae-4da8-a7fa-62dcf54fb0d7)

</details>

#### Capitalized logical operators

<details>

![image](https://github.com/tree-sitter/tree-sitter-php/assets/4176520/cf55c0ac-e9fd-4180-ae5c-82a3bbc46a9c)

</details>

#### Associativity of null-coalescence

<details>

![image](https://github.com/tree-sitter/tree-sitter-php/assets/4176520/e73516d2-fcd7-447f-87da-1147e02314ce)

</details>

**Comment by amaanq** [comment]
use tree-sitter master, it supports the regex i flag

**Comment by CalebDW** [comment]
That would explain it---however, that requirement is not captured in `package.json`

**Comment by CalebDW** [comment]
What's an easy way to compile/install tree-sitter master?

**Comment by amaanq** [comment]
yeah node and master are a bit disjunct atm, my hands are tied but I'd like a new release though 

cargo install --git https://github.com/tree-sitter/tree-sitter

**Comment by calebdw** [comment]
@amaanq, any change we can get a node release soon?

**Comment by amaanq** [comment]
soon hopefully
