### ISSUE TITLE
String backed enums are not recognized

### ISSUE THREAD

**Issue by benfaerber** [tree-sitter/tree-sitter-php#195]
```php
enum Card: string {
    case Jester = "j";
    case Queen = "q";
    case King = "l";
}
```

The strings are colored as if they've failed to parse

**Comment by calebdw** [comment]
This looks to just be a theme issue, everything looks to be parsed just fine:

![image](https://github.com/tree-sitter/tree-sitter-php/assets/4176520/e802cb5e-1942-4e07-91ad-530abeab6bdd)

**Comment by calebdw** [comment]
Actually, an error occurs with double quoted strings:

![image](https://github.com/tree-sitter/tree-sitter-php/assets/4176520/86510e61-e237-49a7-819a-559aafae76db)

This might be a feature though (no expansion allowed)...
