### ISSUE TITLE
Remove JS examples parsing script?

### ISSUE THREAD

**Issue by calebdw** [tree-sitter/tree-sitter-php#202]
@cfroystad, 

I'm moving this to an issue to better track the conversation, please see the following for reference: https://github.com/tree-sitter/tree-sitter-php/commit/fa9bc443a8573750509bebc7cb7266d5ddbe6ede#r132946235

Essentially @amaanq and I would like to remove the js script and stick with the bash script (regardless of what is decided I think we should remove one of them as there's no need for both) but I wanted to make sure you were on board first as you introduced the js script into the codebase.

What are your thoughts?

Thanks!

**Comment by cfroystad** [comment]
I'm fine with removing the JS version in favor of the bash script. This came about as a hack when I started contributing here (using Windows at the time), so no strong opinions.

What I have opinions about is that we keep verifying the repos we parse using the JS script on all platforms to ensure we don't introduce new problems for e.g. Windows while we're developing on our Linux machines :slightly_smiling_face:

**Comment by calebdw** [comment]
Haha it would be a lot easier if everyone just switched to Linux :upside_down_face: 

So what's the actionable path forward? These two statements seem to be contradictory...

> I'm fine with removing the JS version in favor of the bash script.

> that we keep verifying the repos we parse using the JS script on all platforms
