### ISSUE TITLE
bug: nowdoc string parsing breaks, if the identifier contains numbers

### ISSUE THREAD

**Issue by misterunknown** [tree-sitter/tree-sitter-php#209]
### Did you check existing issues?

- [X] I have read all the [tree-sitter docs](https://tree-sitter.github.io/tree-sitter/using-parsers) if it relates to using the parser
- [X] I have searched the existing issues of tree-sitter-php

### Tree-Sitter CLI Version, if relevant (output of `tree-sitter --version`)

tree-sitter 0.20.8

### Describe the bug

Treesitter fails to detect PHP nowdoc syntax correctly, if the identifier contains numbers.

### Steps To Reproduce/Bad Parse Tree

1. Create a PHP file with this content
```
<?php

$myString = <<<'f00bar'
This is a string
f00bar;

class MyClass {
    private int $a;
}
```
2. Parse the file (tree-sitter parse test.php)

Output:
```
(program [0, 0] - [9, 0]
  (php_tag [0, 0] - [0, 5])
  (ERROR [2, 0] - [9, 0]
    (variable_name [2, 0] - [2, 9]
      (name [2, 1] - [2, 9]))
    (heredoc_start [2, 16] - [2, 17])
    (ERROR [2, 17] - [2, 22]
      (integer [2, 17] - [2, 19])
      (name [2, 19] - [2, 22]))
    (nowdoc_body [2, 23] - [8, 1]
      (nowdoc_string [3, 0] - [3, 16])
      (nowdoc_string [3, 16] - [4, 7])
      (nowdoc_string [4, 7] - [6, 15])
      (nowdoc_string [6, 15] - [7, 19])
      (nowdoc_string [7, 19] - [8, 1]))))
/home/marco/tmp/test.php       0 ms    (ERROR [2, 0] - [9, 0])
```

### Expected Behavior/Parse Tree

Tree-sitter should parse nowdoc begin and end correctly.

### Repro

```PHP
<?php

$myString = <<<'f00bar'
This is a string
f00bar;

// Everything since the start of the nowdoc gets interpreted as a nowdoc string
class MyClass {
    private int $a;
}
```

**Comment by calebdw** [comment]
Good catch, I created a PR to fix this. Although I have to ask, why are you using digits in the heredoc identifier? Sure it's valid PHP, but most of the time I see language identifiers for tree-sitter injection

**Comment by misterunknown** [comment]
Well, I use the nowdoc syntax for embedding very large chunks of other code in my PHP application and want to make absolutely sure that nothing accidentially ends the string midway through. I therefore use a random hash, which naturally contains numbers. Thus far, I replaced the numbers in the identifiers, but I figured it's worth to file this bug.
