### ISSUE TITLE
bug: `munmap_chunk(): invalid pointer` in neovim when built with `-Os` flag

### ISSUE THREAD

**Issue by liljaylj** [tree-sitter/tree-sitter-php#238]
### Did you check existing issues?

- [ ] I have read all the [tree-sitter docs](https://tree-sitter.github.io/tree-sitter/using-parsers) if it relates to using the parser
- [X] I have searched the existing issues of tree-sitter-php

### Describe the bug

when trying to open some php files with injections I get `munmap_chunk(): invalid pointer`. after bisecting and looking at `tree-sitter-php`'s makefile and `nvim-treesitter`'s source code, I found `nvim-treesitter` includes compiler flag `-Os` (optimize for size). when build with this flag, parser coredumps.

### Steps To Reproduce/Bad Parse Tree

1. install `nvim-treesitter` plugin in neovim
2. install `php` parser with `:TSInstall php`, or update to latest version `:TSUpdate php`
3. open reproducer code below
4. neovim crash

### Expected Behavior/Parse Tree

1. install `nvim-treesitter` plugin in neovim
2. install `php` parser with `:TSInstall php`, or update to latest version `:TSUpdate php`
3. open reproducer code below
4. no crash

### Repro

```PHP
<?php

$query = <<<SQL
select * from users;
SQL;
```

**Comment by przepompownia** [comment]
Thanks for reporting: I have no idea how to reproduce https://github.com/nvim-treesitter/nvim-treesitter/issues/6573 in a way independent of Neovim.

**Comment by przepompownia** [comment]
For comparison, `php_only` crashes for me on https://raw.githubusercontent.com/phpactor/phpactor/ac99b4d8831eb5a249a2b1788cbb5b64a4a1c61c/lib/Diff/Tests/RangesForDiffTest.php (`php` does not).

**Comment by quaternion7** [comment]
I'm having that problem, and i noticed it does not crash on literal injection (by initializing the heredoc with single quotes, so no string interpolation):
`<?php
$query = <<<'SQL'
select * from users;
SQL;`

**Comment by quaternion7** [comment]
As a workaround, I downgraded nvim-treesitter to the commit #c579d18, which is the one just before the php parser change:
```lua
-- Using Packer 
use { 'nvim-treesitter/nvim-treesitter', run = ':TSUpdate',
    commit = 'c579d18',
    requires = {
        { 'nvim-treesitter/nvim-treesitter-textobjects' },
    }
}
```

**Comment by liljaylj** [comment]
my workaround is this - I built the project from this repository using the Makefile from here. it does not use the `-Os` flag. then I, for now, have manually replaced `php.so` and `php_only.so` files in the `./parser/` directory in `nvim-treesitter`.

next time `php`, `php_only` parsers are updated in lockfile

no crashes yet =)

**Comment by whleucka** [comment]
I am experiencing `munmap_chunk(): invalid pointer` issue as well.
I can now open the problematic files using ts commit `c579d18`
However, I now see other errors (with no highlighting) using vim.lsp.buf.hover(), for example.

![image](https://github.com/tree-sitter/tree-sitter-php/assets/71740767/5f709377-49da-491b-b3cb-ac3bd799b066)

**Comment by HalibutGitWiz** [comment]
Same issue here, downgrading nvim-treesitter to commit c579d18 solved it for me too. Thanks for sharing @quaternion7

**Comment by amaanq** [comment]
https://github.com/tree-sitter/tree-sitter-php/commit/27afeb02e49ff30acd17b67897b1c0114561a38c
