### ISSUE TITLE
bug: wrong js highlight in php

### ISSUE THREAD

**Issue by cxwx** [tree-sitter/tree-sitter-php#240]
### Did you check existing issues?

- [X] I have read all the [tree-sitter docs](https://tree-sitter.github.io/tree-sitter/using-parsers) if it relates to using the parser
- [X] I have searched the existing issues of tree-sitter-php

### Describe the bug

The origin highlight for php in neovim is fine like below
![CodeSnap_2024-05-08_at_22:27:15](https://github.com/tree-sitter/tree-sitter-php/assets/6235641/813471f2-a54b-405b-89a3-cfd8a54beefe)
but if I use treesitter-php
it looks like
<img width="424" alt="截屏2024-05-08 22 33 55" src="https://github.com/tree-sitter/tree-sitter-php/assets/6235641/3fd357a5-078b-46b9-bf0f-4feede91430a">
and the second value
```
var begintime = 。。。
```
is not correctly highlight

because I use 
`<?php ... ?>` without `"<?php ...?>"`
but if the echo value is json, I could not add `" "` outside `<?php ... ?>
which cause this problem.

### Steps To Reproduce/Bad Parse Tree

1. using treesitter-php
2. 
<script>
        var ttData = <?php echo $tt_data; ?>;
        var data_400 = <?php echo $adata400; ?>;
</script>

without `" ...   "`

### Expected Behavior/Parse Tree

correct rightly

### Repro

```PHP
html>

<head>
    <title>test?</title>
</head>

<body>
    <canvas id="myChart"></canvas>
<script>
let ttData = <?php echo $tt_data; ?>;
var beginTime = '<?php echo $begintime; ?>';
var endTime = '<?php echo $endtime; ?>';
</script>
</body>

</html>
```

**Comment by calebdw** [comment]
As you can see here, the php highlights are working properly:

![image](https://github.com/tree-sitter/tree-sitter-php/assets/4176520/d4e13c0b-e5bc-41e0-8c4d-4f9b7c4f484c)

The issue you're experiencing has to do with javascript highlight conflicts/overrides:

![image](https://github.com/tree-sitter/tree-sitter-php/assets/4176520/dc52c95d-d1bb-45cd-9eda-196f9c53230d)

However, this would have to be dealt with on the nvim-treesitter side of things.
