### ISSUE TITLE
bug: heredoc injects javascript highlighting for 'javascript' but not 'js'

### ISSUE THREAD

**Issue by kylehardinge** [tree-sitter/tree-sitter-php#241]
### Did you check existing issues?

- [X] I have read all the [tree-sitter docs](https://tree-sitter.github.io/tree-sitter/using-parsers) if it relates to using the parser
- [X] I have searched the existing issues of tree-sitter-php

### Tree-Sitter CLI Version, if relevant (output of `tree-sitter --version`)

tree-sitter 0.20.8

### Describe the bug

I am working with a codebase where all of the javascript heredocs are titled JS and would expect the javascript tree sitter parsing to be applied. I tested the heredocs by titling them with JAVASCRIPT and that works as expected.

This screenshot shows a JS heredoc without parsing.
![Screenshot 2024-05-15 at 15 51 32](https://github.com/tree-sitter/tree-sitter-php/assets/52141268/57ceb329-0d5e-44ca-b680-f9d7a2d11ef6)

This screenshot shows a JAVASCRIPT heredoc with parsing.
![Screenshot 2024-05-15 at 15 51 01](https://github.com/tree-sitter/tree-sitter-php/assets/52141268/d114fbda-30ec-40c0-b2df-f12c4a686f70)
 

### Steps To Reproduce/Bad Parse Tree

1. tree-sitter-php installed
2. create a heredoc and title it JS
3. there should be no highlighting

### Expected Behavior/Parse Tree

The tree sitter parsing for javascript should be applied to js heredocs.

### Repro

```PHP
// Example code that causes the issue
function foo() {
  // Code that fails to parse, or causes an error
}
```

**Comment by amaanq** [comment]
does not belong here, this is the parser repo - file an issue with the tool that leverages this parser
