### ISSUE TITLE
bug: SQL injection works with heredoc, but now with nowdoc

### ISSUE THREAD

**Issue by greg0ire** [tree-sitter/tree-sitter-php#243]
### Did you check existing issues?

- [X] I have read all the [tree-sitter docs](https://tree-sitter.github.io/tree-sitter/using-parsers) if it relates to using the parser
- [X] I have searched the existing issues of tree-sitter-php

### Tree-Sitter CLI Version, if relevant (output of `tree-sitter --version`)

tree-sitter 0.22.5

### Describe the bug

SQL is not recognized as such when enclosed in nowdoc.

### Steps To Reproduce/Bad Parse Tree

```
      right: (nowdoc) ; [130:16 - 135:3]
       identifier: (heredoc_start) ; [130:20 - 22]
       value: (nowdoc_body) ; [130:24 - 134:1]
        (nowdoc_string) ; [131:1 - 24]
        (nowdoc_string) ; [131:25 - 132:22]
        (nowdoc_string) ; [132:23 - 133:18]
        (nowdoc_string) ; [133:19 - 134:1]
       end_tag: (heredoc_end) ; [134:2 - 135:3]
```

### Expected Behavior/Parse Tree

```
      right: (nowdoc) ; [130:16 - 135:3]
       identifier: (nowdoc_start) ; [130:20 - 22]
       value: (nowdoc_body) ; [130:24 - 134:1]
        (statement) ; [131:1 - 133:18]
         (create_table) ; [131:1 - 133:18]
          (keyword_create) ; [131:1 - 6]
          (keyword_table) ; [131:8 - 12]
          (object_reference) ; [131:14 - 22]
           name: (identifier) ; [131:14 - 22]
          (column_definitions) ; [131:24 - 133:18]
           (column_definition) ; [132:5 - 20]
            name: (identifier) ; [132:5 - 7]
            type: (varchar) ; [132:9 - 20]
             (keyword_varchar) ; [132:9 - 15]
             size: (literal) ; [132:18 - 19]
           (column_definition) ; [133:5 - 12]
            name: (identifier) ; [133:5 - 7]
            type: (keyword_text) ; [133:9 - 12]
           (keyword_having) ; [133:14 - 17]
        (keyword_having) ; [134:1 - 1]
        (string_content) ; [131:1 - 24]
        (string_content) ; [132:1 - 22]
        (string_content) ; [133:1 - 18]
        (string_content) ; [134:1 - 1]
       end_tag: (nowdoc_end) ; [135:1 - 3]
```

### Repro

```PHP
// Example code that causes the issue
function foo() {
  // Code that fails to parse, or causes an error
        $sql = <<<'SQL'
CREATE TABLE dbal_1779 (
    foo VARCHAR (64) ,
    bar TEXT (100)
)
SQL;
}
```

Maybe the issue is that the tree shows `heredoc_start` and not `nowdoc_start`, if such a thing exists…

**Comment by calebdw** [comment]
> Maybe the issue is that the tree shows heredoc_start and not nowdoc_start

No that's not the issue, the Nowdoc reuses the same heredoc_{start,end} nodes

**Comment by calebdw** [comment]
Issue is that the `heredoc_end` is sometimes including the whitespace:

![image](https://github.com/tree-sitter/tree-sitter-php/assets/4176520/d06baa2b-29b4-4ba9-bfda-20eba2b01f23)

However, does not seem to do this if there's a comma:

![image](https://github.com/tree-sitter/tree-sitter-php/assets/4176520/a1880de4-6030-4fb3-b590-5523145a7f68)
