### ISSUE TITLE
bug: Error while generating a wasm

### ISSUE THREAD

**Issue by maheshbaliga** [tree-sitter/tree-sitter-php#248]
### Did you check existing issues?

- [X] I have read all the [tree-sitter docs](https://tree-sitter.github.io/tree-sitter/using-parsers) if it relates to using the parser
- [X] I have searched the existing issues of tree-sitter-php

### Tree-Sitter CLI Version, if relevant (output of `tree-sitter --version`)

tree-sitter 0.22.6 (b40f342067a89cd6331bf4c27407588320f3c263)

### Describe the bug

```
scanner.c:1:10: fatal error: '../../common/scanner.h' file not found
    1 | #include "../../common/scanner.h"
      |          ^~~~~~~~~~~~~~~~~~~~~~~~
1 error generated.
emcc: error: '/emsdk/upstream/bin/clang -target wasm32-unknown-emscripten -fignore-exceptions -fPIC -mllvm -combiner-global-alias-analysis=false -mllvm -enable-emscripten-sjlj -mllvm -disable-lsr --sysroot=/emsdk/upstream/emscripten/cache/sysroot -DEMSCRIPTEN -Werror=implicit-function-declaration -Xclang -iwithsysroot/include/fakesdl -Xclang -iwithsysroot/include/compat -Os -fno-exceptions -fvisibility=hidden -I. scanner.c -c -o /tmp/emscripten_temp_04ryzxba/scanner_0.o' failed (returned 1)
emcc command failed
```
The issue seems to be have been fixed as part of PR#[3337](https://github.com/tree-sitter/tree-sitter/pull/3337), but it is still throwing an error.

### Steps To Reproduce/Bad Parse Tree

I run this command `npx tree-sitter build --wasm node_modules/tree-sitter-php/php/ --output tree-sitter-php.wasm`, which results in the above error.  

### Expected Behavior/Parse Tree

Successful build and WASM gets generated.

**Comment by amaanq** [comment]
I can confirm if `npx tree-sitter --version` shows that it's 0.22.6 it works, you are probably on an older version

**Comment by maheshbaliga** [comment]
@amaanq I have mentioned the version in the issue description which is 0.22.6, and it is not working.
