### ISSUE TITLE
bug: opening PHP required for highlighting to work

### ISSUE THREAD

**Issue by HalibutGitWiz** [tree-sitter/tree-sitter-php#253]
### Did you check existing issues?

- [X] I have read all the [tree-sitter docs](https://tree-sitter.github.io/tree-sitter/using-parsers) if it relates to using the parser
- [X] I have searched the existing issues of tree-sitter-php

### Describe the bug

The opening `<?php` or `<?` is required for highlighting to work. This makes sense for a PHP file, since it can contain other languages, such as HTML.

But it's weird when embedding PHP code in another file, like a Markdown document. Basically, you have to tell Treesitter that the content is PHP twice : once when creating the code block, and a second time by adding the PHP tag inside the block.

Screenshot taken using Neovim 0.10.1 and nvim-treesitter v0.9.2

![Screenshot_20240825_115250](https://github.com/user-attachments/assets/961fae95-f996-41fa-a733-301cf7498836)

### Steps To Reproduce/Bad Parse Tree

1. Open a Markdown document (or any other language that can include code blocks)
2. Include a PHP block with an opening tag
3. Include another PHP block without the opening tag

### Expected Behavior/Parse Tree

Expected : proper highlighting in both blocks
Actual : highlighting only when opening tag is used

### Repro

~~~
Some text

```php
function test($test) {
    echo $test;
}
```

Some other text

```php
<?php
function test($test) {
    echo $test;
}
```

Some other text

```php
<?
function test($test) {
    echo $test;
}
```

Some other text
~~~

**Comment by calebdw** [comment]
This is not a bug, use the `php_only` parser
