### ISSUE TITLE
bug: failed pypi deployment

### ISSUE THREAD

**Issue by calebdw** [tree-sitter/tree-sitter-php#254]
@amaanq, I just tried publishing the v0.23.0 release and the pypi deployment failed for some reason: https://github.com/tree-sitter/tree-sitter-php/actions/runs/10589378261/job/29343393721

Any ideas why?

**Comment by amaanq** [comment]
Not sure why - but using python 3.12 has caused this to fail, even though it should install setuptools anyways. I updated the upstream workflow to use 3.11 by default now

**Comment by amaanq** [comment]
@calebdw python publishing is fixed and the bindings are updated for 0.23 - just a little note on tagging a new release:

Update common.mak, package.json, pyproject.toml, and Cargo.toml with the new version
Run `npm i` and `cargo update` to update both lockfiles
Commit **six** files, tag the commit with `vx.y.z`, and push the commit + tag :slightly_smiling_face:
