### ISSUE TITLE
feature: The difference between Grammar php and php_only

### ISSUE THREAD

**Issue by Vanillma** [tree-sitter/tree-sitter-php#257]
### Did you check the tree-sitter docs?

- [X] I have read all the [tree-sitter docs](https://tree-sitter.github.io/tree-sitter/using-parsers) if it relates to using the parser

### Is your feature request related to a problem? Please describe.

Hi, I'm currently learning PHP and trying to set up Neovim with the Tree-sitter plugin for PHP. I noticed there are two grammar versions available for installation: php and php_only.

Could you please explain the difference between these two versions? Are both required for a basic PHP setup?

I've searched online and even asked AI, but I couldn't find any specific information about the php_only format. The closest I found was a configuration setting in StyleCI.

### Describe the solution you'd like

Please add some more details to the repository :))

### Describe alternatives you've considered

thanks.

**Comment by calebdw** [comment]
php_only is just php. The `php` parser parses php and html

**Comment by Vanillma** [comment]
> php_only is just php. The `php` parser parses php and html

Thanks for your quick reply...I'll close this issue...but I think it's better to add this short description to the main page of the repository...it might help people...thanks♥️

**Comment by calebdw** [comment]
See related: #168
