### ISSUE TITLE
bug: Incopatible with treesitter-html in neovim

### ISSUE THREAD

**Issue by RepinsPL** [tree-sitter/tree-sitter-php#261]
### Did you check existing issues?

- [X] I have read all the [tree-sitter docs](https://tree-sitter.github.io/tree-sitter/using-parsers) if it relates to using the parser
- [X] I have searched the existing issues of tree-sitter-php

### Tree-Sitter CLI Version, if relevant (output of `tree-sitter --version`)

tree-sitter 0.23.0

### Describe the bug

Neovim with installed both "html" and "php" parsers for some .php files (with multiple php/html blocks) Treesitter is generating propably corrupted tree resulting in breaking some functions (indentation etc.) for php.
Uninstalling "html" parser solves the issue, but of course it's not a solution.

### Steps To Reproduce/Bad Parse Tree

1. Install parsers both parsers "html" and "php".
2. Make sure to have treesitter indentations enabled:
```
indent = {
    enable = true,
},
```
Create .php file with content:
```
<?php
	echo(1);
?>
<link />
<?php
	echo(2);
?>
<link />
```
Place cursor in insert mode after 'echo(2);' and press Enter.

Result(bug): Indentation both for line with 'echo(2);' and new line are removed. Probably generated tree is corrupted, because some other plugins also don't work for second PHP block (for example "HiPhish/rainbow-delimiters.nvim" is coloring brackets only in first PHP block, not in the second one).

:InspectTree for bugged example (both HTML and PHP parsers installed):
```
(program ; [0, 0] - [8, 0]
  (document ; [3, 0] - [8, 0]
    (element ; [3, 0] - [3, 8]
      (self_closing_tag ; [3, 0] - [3, 8]
        (tag_name))) ; [3, 1] - [3, 5]
    (element ; [7, 0] - [7, 8]
      (self_closing_tag ; [7, 0] - [7, 8]
        (tag_name)))) ; [7, 1] - [7, 5]
  (php_tag) ; [0, 0] - [0, 5]
  (echo_statement ; [1, 1] - [1, 9]
    (parenthesized_expression ; [1, 5] - [1, 8]
      (integer))) ; [1, 6] - [1, 7]
  (text_interpolation ; [2, 0] - [4, 5]
    (text) ; [3, 0] - [4, 0]
    (php_tag)) ; [4, 0] - [4, 5]
  (echo_statement ; [5, 1] - [5, 9]
    (parenthesized_expression ; [5, 5] - [5, 8]
      (integer))) ; [5, 6] - [5, 7]
  (text_interpolation ; [6, 0] - [8, 0]
    (text))) ; [7, 0] - [8, 0]
```

### Expected Behavior/Parse Tree

Indentation of line "echo(2);" should be preserved. Other plugins should work for all PHP blocks.

:InspectTree for working example (only PHP parser installed):
```
(program ; [0, 0] - [8, 0]
  (php_tag) ; [0, 0] - [0, 5]
  (echo_statement ; [1, 1] - [1, 9]
    (parenthesized_expression ; [1, 5] - [1, 8]
      (integer))) ; [1, 6] - [1, 7]
  (text_interpolation ; [2, 0] - [4, 5]
    (text) ; [3, 0] - [4, 0]
    (php_tag)) ; [4, 0] - [4, 5]
  (echo_statement ; [5, 1] - [5, 9]
    (parenthesized_expression ; [5, 5] - [5, 8]
      (integer))) ; [5, 6] - [5, 7]
  (text_interpolation ; [6, 0] - [8, 0]
    (text))) ; [7, 0] - [8, 0]
```

### Repro

Output of :checkhealth nvim-treesitter
```
Parser/Features         H L F I J
  - c                   ✓ ✓ ✓ ✓ ✓
  - html                ✓ ✓ ✓ ✓ ✓
  - lua                 ✓ ✓ ✓ ✓ ✓
  - markdown            ✓ . ✓ ✓ ✓
  - markdown_inline     ✓ . . . ✓
  - php                 ✓ ✓ ✓ ✓ ✓
  - query               ✓ ✓ ✓ ✓ ✓
  - vim                 ✓ ✓ ✓ . ✓
  - vimdoc              ✓ . . . ✓
```

**Comment by calebdw** [comment]
This parser has nothing to do with the indentation behaviour in Neovim. Treesitter based indentation is provided by [
nvim-treesitter](https://github.com/nvim-treesitter/nvim-treesitter) and their respective indentation queries. Their injection queries injects `html` into this parsers `text` node and the indentation behaviour is governed by the current node's language.

That said, the indentation being performed is correct. Treesitter looks at the surrounding code to determine when a branch should be created (like if `{` is created). In this case, the code in the php tag is a top level statement that should not be indented:

```php
<?php
	echo(1);
?>
// should be
<?php
echo(1);
?>
```

**Comment by RepinsPL** [comment]
Thanks for the answer. :)

But indentation is just a visible symptom - please look at provided result of ":inspectTree" - one with incorrect behaviours has the second "<?php" block covered twice - first as html entity "(document ; [3, 0] - [8, 0]" (provided propably by html paser) and second time the right way by php parser.

Due to that fact, second part is not interpreted in correct way in may scenarios:
1) Pressing enter at the end of line resulting in deleting indentation (even if it is in some nested loop block etc. and should be intended). 
2) Parsing it by plugins such as "HiPhish/rainbow-delimiters.nvim which is coloring brackets
...and many more.

I'm don't know well the architecture of treesitter (yet! ;)) - does php parser is only responsible for generating tree, or is it also responsible for somehow interpreting it?

**Comment by RepinsPL** [comment]
Finally found a good workaround/solution for this problem:
In your treesitter-php injections.scm file (in my case: ~/.local/share/nvim/lazy/nvim-treesitter/queries/php/injections.scm) remove or comment line:
(#set! injection.combined)

Everything will work fine, just separate html parts in treesitter tree won't be marged in one large part, which will may result only a little performance downgrade if any.
