### ISSUE TITLE
To PHPDocumentor or not to PHPDocumentor

### ISSUE THREAD

**Issue by Ben3eeE** [tree-sitter/tree-sitter-php#33]
:wave: This is mostly a question. Feel free to close as a `wontfix` if you want. I just wanted to bring it up as it differs from a textmate rule we have had in Atom for the past 5 years 🙂 

The textmate grammar has [since forever](https://github.com/atom/language-php/blame/efbdd0074d7e2a6602f12dd85ce10dabbeb1817f/grammars/php.json#L1577-L1579) highlighted PHPDocumentor comments as invalid if they don't follow the syntax rules. This is from the initial commit 5 years ago 😱 

It is still technically valid PHP syntax to not follow PHPDocumentor so tree-sitter-php is technically not wrong but there is a difference from the old textmate highlighting in Atom. Do you consider these things in tree-sitter or not? 🙂 

**Textmate**
![image](https://user-images.githubusercontent.com/1058982/46890909-864e5000-ce68-11e8-8d79-4eb802375513.png)

```
Scopes at Cursor

text.html.php
meta.embedded.block.php
source.php
comment.block.documentation.phpdoc.php
invalid.illegal.missing-asterisk.phpdoc.php
```

**tree-sitter**
![image](https://user-images.githubusercontent.com/1058982/46890924-96fec600-ce68-11e8-914f-3c8a8bd71162.png)

```
Scopes at Cursor

text.html.php
source.php
comment.block
```

**Comment by Ingramz** [comment]
If we want to get something up and running real quick, I suppose it is better to skip this initially.

Also, if possible, perhaps it could be implemented this time so that it wouldn't be coupled to the main PHP grammar. I haven't had a chance to tinker around with tree-sitter much, so I cannot really tell if this is feasible or not.

**Comment by Arcanemagus** [comment]
You can compose tree-sitter grammars (https://github.com/atom/atom/pull/17551) but I'm not sure myself how (or if) that would work for comment nodes.

**Comment by Ben3eeE** [comment]
Make a parser for doc comments and use injections if we want to add this to Atom. See https://github.com/tree-sitter/tree-sitter-jsdoc

**Comment by Arcanemagus** [comment]
Also of note is how it was integrated into `language-javascript`: https://github.com/atom/language-javascript/pull/629
