### ISSUE TITLE
Variables that will be expanded in double quoted strings are not parsed as variables

### ISSUE THREAD

**Issue by Ben3eeE** [tree-sitter/tree-sitter-php#34]
http://php.net/manual/en/language.types.string.php#language.types.string.parsing

**Program:**
```php
<?php
$juice = "apple";

echo "He drank some $juice juice.".PHP_EOL;
// Invalid. "s" is a valid character for a variable name, but the variable is $juice.
echo "He drank some juice made of $juices.";
// Valid. Explicitly specify the end of the variable name by enclosing it in braces:
echo "He drank some juice made of ${juice}s.";
?>
```

**Output:**
```
He drank some apple juice.
He drank some juice made of .
He drank some juice made of apples.
```

**Parser:**
All of these variables are parsed as `string`:
```
text.html.php
program
echo_statement
string
```

**Version:**
0.13.0

**Comment by patrickt** [comment]
Oof, that’s tricky as well.

**Comment by maxbrunsfeld** [comment]
Seems like strings work *somewhat* similarly to double quoted strings in bash? Here's our current rule for that in the bash parser: https://github.com/tree-sitter/tree-sitter-bash/blob/5203b504db454180de58af6f0ea6fc10df47b487/grammar.js#L417-L430.
