### ISSUE TITLE
NOWDOC test expects HEREDOC and NOWDOC is not working locally but passes on CI

### ISSUE THREAD

**Issue by Ben3eeE** [tree-sitter/tree-sitter-php#36]
https://github.com/tree-sitter/tree-sitter-php/blob/8443558ac33a8dd4206e5d8fdf80495be0062654/corpus/expressions.txt#L143-L157

This test fails locally:

```
    ✗ Nowdocs
        »
        actual expected

        (program (ERROR) (text) (echo_statement (binary_expression (function_call_expression (qualified_name (name)) (arguments)) (qualified_name (name)))) (expression_statement (qualified_name (name))))heredoc)))
```

I don't know why it doesn't fail on CI but does locally. It seems that NOWDOC is expected to parsed as HEREDOC from the test however which is wrong.

Also testing the tests code in Atom when running https://github.com/atom/language-php/pull/303 confirms that it's parsed the same way as the test.

Expected should be:
```
(program (expression_statement (nowdoc)))
```

http://php.net/manual/en/language.types.string.php#language.types.string.syntax.heredoc
http://php.net/manual/en/language.types.string.php#language.types.string.syntax.nowdoc
https://wiki.php.net/rfc/heredoc-with-double-quotes

**Comment by lukedan** [comment]
This is likely due to CRLF line endings. See also tree-sitter/tree-sitter#913.

**Comment by maxbrunsfeld** [comment]
I think this will be fixed in https://github.com/tree-sitter/tree-sitter-php/pull/55.

**Comment by patrickt** [comment]
Thanks to @maxbrunsfeld for the fix!
