### ISSUE TITLE
Parse error on exponentiation with augmented assignment

### ISSUE THREAD

**Issue by Sjord** [tree-sitter/tree-sitter-php#96]
```
<?php
$a ** $c += $b;
```

Actual:

```
(program
  (php_tag)
  (expression_statement
    (exponentiation_expression
      (variable_name
        (name))
      (ERROR
        (variable_name
          (name)))
      (variable_name
        (name)))))
test2.php	0 ms	(ERROR)
```

Test case:

```
==========================
Precedence between exponentiation and augmented assignment
==========================

<?php
$a ** $c += $b;

---

(program
  (php_tag)
  (expression_statement
    (exponentiation_expression
      (variable_name
        (name))
        (augmented_assignment_expression
          (variable_name
            (name))
          (variable_name
            (name))))))
```

**Comment by cfroystad** [comment]
Fixed in master. Thanks for reporting!

Am I right in assuming you have some kind of marvelous test suite running somewhere? Is it public (and preferably easy to run)?

**Comment by Sjord** [comment]
Yes, it's quite marvelous. I made [a script](https://github.com/Sjord/tree-sitter-php/blob/test-precedence/operators.py) to generate test cases for precedence. It's quite slow, ugly and fragle, but with some hand-holding it can create a lot of test cases for precedence. It creates expressions with various combinations of operators. For every combination, it adds parentheses in two different ways. E.g. `($a + $b) * $c` and `$a + ($b * $c)`. It then runs PHP with these expression and the original expression, to determine which is the correct precedence. It parses the correct expression with tree-sitter, and removes the `parenthesized_expression` nodes from the output to get the expected output, and puts that in a test case. This results in [1922 test cases](https://github.com/Sjord/tree-sitter-php/blob/test-precedence/test/corpus/precedence.txt) on precedence. This is just a normal tree-sitter test, so it's easy to run.

**Comment by cfroystad** [comment]
This looks really useful and is a great inspiration for improving the robustness and correctness of the parser!

I'll try to find some spare time in the near future to play around with it
