### ISSUE TITLE
Breaks auto-indent in neovim

### ISSUE THREAD

**Issue by Geraint** [tree-sitter/tree-sitter-php#99]
I'm using neovim v0.5.0:

```
$ nvim --version
NVIM v0.5.0
Build type: Release
LuaJIT 2.1.0-beta3
Compilation: /usr/bin/cc -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -DNVIM_TS_HAS_SET_MATCH_LIMIT -O2 -DNDEBUG -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wmissing-prototypes -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fno-common -fdiagnostics-color=always -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -DMIN_LOG_LEVEL=3 -I/root/opt/neovim/build/config -I/root/opt/neovim/src -I/root/opt/neovim/.deps/usr/include -I/usr/include -I/root/opt/neovim/build/src/nvim/auto -I/root/opt/neovim/build/include
Compiled by root@REDACTED

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/local/share/nvim"

Run :checkhealth for more info
```

I have the treesitter plugin installed, and this config:

```
lua <<EOF
require'nvim-treesitter.configs'.setup {
    ensure_installed = { "javascript" },
    highlight = {
        enable = true,
    }
}
EOF
```

I I don't install the PHP parser, I don't get tree-sitter syntax highlighting, but auto-indent works as expected

If I *do* install the PHP parser, I get tree-sitter syntax highlighting, but autoindenting stops working.  Whenever I hit the return key, I'm on column 0, no matter how the preceding line is indented (in a method, in a `if` statement, etc).

If I issue

```
:syntax on
```

... indentation starts working again, but if I switch to another buffer and then back again, syntax has been turned back off and auto indentation is once again broken.

I have tried adding `syntax on` to `after/ftplugin/php.vim`, but it does not help.

**Comment by cfroystad** [comment]
Could you please help me understand what makes this a tree-sitter-php issue rather than a neovim integration issue? (disclaimer: I know nothing about neovim and its integration and may be missing something obvious)

**Comment by patrickt** [comment]
Yeah, this should be reported to Neovim. Tree-sitter provides no information or heuristics for indentation; it’s Neovim’s job to do that integration.

**Comment by Geraint** [comment]
Sorry for having reported this to the wrong project.

In case any one else happens across this, I reported it (and got it resolved) here: https://github.com/nvim-treesitter/nvim-treesitter/issues/1742

**Comment by still-dreaming-1** [comment]
If you want to use treesitter indentation instead, you can use this:

```
require 'nvim-treesitter.configs'.setup {
  indent = {
    enable = true
  }
}
```
